log_level: info
db:
  uri: mongodb://localhost:27017/
  name: registrar_db
listener:
  watchers:
    - network: kusama
      endpoint: ws://localhost:8000
    - network: polkadot
      endpoint: ws://localhost:8001
  matrix:
    enabled: false
    homeserver: homeserver
    username: username
    password: password
    db_path: db_path
    admins: null
  display_name:
    enabled: true
    limit: 0.85
notifier:
  api_address: 0.0.0.0:8000
  cors_allow_origin:
    - 'https://mydomain.com'
  display_name:
    enabled: true
    limit: 0.85
