log_level: info
matrix:
  enabled: true
  homeserver: https://matrix.org
  username: regbot
  password: abc123
  security_key: 'EfT0 1WXL nIi8 v1Zx 15c8 B8Ux bKdS fLUZ 5uVk zje7 KYFj ZiLf'
  admins:
    - '@sara:matrix.org'
    - '@bill:matrix.org'
